# Generated by Django 2.1.2 on 2018-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('addr', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=11)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'doing'), ('1', 'complete'), ('2', 'failure')], default='0', max_length=2)),
            ],
        ),
    ]
